### ISSUE TITLE
home_root data_root

### ISSUE THREAD

**Issue by 11051911** [huangmozhi9527/ConMH#1]
What do home_root and data_root in the code refer to, look forward to your reply

**Comment by huangmozhi9527** [comment]
Hi, home_root is the file path to your code, data_root is the file path to your dataset.

**Comment by 11051911** [comment]
Thank you very much for your work, it is a very interesting paper, but I have not found the error for a long time.
(conmh) G:\scSSA\scSSA-main\ConMH-main>python train.py --gpu 0 --config configs/conmh_fcv.py 
Traceback (most recent call last):
  File "train.py", line 130, in <module>
    main()
    cfg = Config.fromfile(args.config)
  File "G:\scSSA\scSSA-main\ConMH-main\configs\config.py", line 94, in fromfile
    return Config(cfg_dict, filename=filename)
  File "G:\scSSA\scSSA-main\ConMH-main\configs\config.py", line 120, in __init__
    super(Config, self).__setattr__('_text', f.read())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xb9 in position 661: illegal multibyte sequence
Yours sincerely.

> Hi, home_root is the file path to your code, data_root is the file path to your dataset.

**Comment by huangmozhi9527** [comment]
It seems that you are using windows to run the code, and this problem is caused by different encoding types.
You can try to change the code in https://github.com/huangmozhi9527/ConMH/blob/7b5b20c77e46f6b7e225134ccdbaa870a094e367/configs/config.py#L119
from

> with open(filename, 'r') as f:

to 

> with open(filename, 'r', encoding='utf-8') as f:
